name: Hugo tool cache
on: 
  push:
  workflow_dispatch:
  
env:
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_OWNER: ${{ github.repository_owner }}
  
jobs:
  upload_tool_cache:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          

      - run: npm ci
      - run: hugo --baseURL https://${REPO_OWNER}.github.io/${REPO_NAME} --minify

      - name: Deployment
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }} # <- must be same branch as given above
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public


      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{runner.tool_cache}}/tool_cache.tar.gz
